spring:
  application:
    name: tools-box

logging:
  config: classpath:log4j2.xml
  level:
    org.springframework: info
    _org.springframework: info

avalon:
  trace:
    stack-limit: 10
  thread-pool:
    core-pool-size: 10
    max-pool-size: 10
    queue-capacity: 100
    keep-alive-time: 60